# app/prompts

from .profile_analysis import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE
from .content_opportunity import (
    OPPORTUNITY_SYSTEM_PROMPT,
    OPPORTUNITY_USER_PROMPT_TEMPLATE,
)
from .message_generation import MSG_SYSTEM_PROMPT, MSG_USER_PROMPT_TEMPLATE
from .relationship_maintenance import (
    MAINTENANCE_SYSTEM_PROMPT,
    MAINTENANCE_USER_PROMPT_TEMPLATE,
)
from .follow_up_message import (
    FOLLOWUP_SYSTEM_PROMPT,
    FOLLOWUP_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "SYSTEM_PROMPT",
    "USER_PROMPT_TEMPLATE",
    "OPPORTUNITY_SYSTEM_PROMPT",
    "OPPORTUNITY_USER_PROMPT_TEMPLATE",
    "MSG_SYSTEM_PROMPT",
    "MSG_USER_PROMPT_TEMPLATE",
    "MAINTENANCE_SYSTEM_PROMPT",
    "MAINTENANCE_USER_PROMPT_TEMPLATE",
    "FOLLOWUP_SYSTEM_PROMPT",
    "FOLLOWUP_USER_PROMPT_TEMPLATE",
]
