warehouse:
  TH:
    name: "The Chinese mainland Pickup Warehouse"
    value: ""
  VN:
    name: "The Chinese mainland Pickup Warehouse"
    value: ""
  MY:
    name: "The Chinese mainland Pickup Warehouse"
    value: ""
